//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabajoSocial
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TRABAJO_SOCIALEntities : DbContext
    {
        public TRABAJO_SOCIALEntities()
            : base("name=TRABAJO_SOCIALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbBitacora> tbBitacora { get; set; }
        public virtual DbSet<tbEspecialidades> tbEspecialidades { get; set; }
        public virtual DbSet<tbPacientes> tbPacientes { get; set; }
        public virtual DbSet<tbPacienteXEspecialidad> tbPacienteXEspecialidad { get; set; }
        public virtual DbSet<tbUsuario> tbUsuario { get; set; }
        public virtual DbSet<VW_Usuario> VW_Usuario { get; set; }
    
        public virtual ObjectResult<string> PA_InsertarUsuario(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PA_InsertarUsuario", usernameParameter, passwordParameter);
        }
    }
}
