//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabajoSocial
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEspecialidades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbEspecialidades()
        {
            this.tbBitacora = new HashSet<tbBitacora>();
            this.tbPacienteXEspecialidad = new HashSet<tbPacienteXEspecialidad>();
        }
    
        public int Esp_Id { get; set; }
        public string Esp_Descripcion { get; set; }
        public string Esp_UsuarioCrea { get; set; }
        public Nullable<System.DateTime> Esp_Fecha_Crea { get; set; }
        public string Esp_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> Esp_FechaModifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbBitacora> tbBitacora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPacienteXEspecialidad> tbPacienteXEspecialidad { get; set; }
    }
}
