//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabajoSocial
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPacientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbPacientes()
        {
            this.tbBitacora = new HashSet<tbBitacora>();
            this.tbPacienteXEspecialidad = new HashSet<tbPacienteXEspecialidad>();
        }
    
        public int Pte_Id { get; set; }
        public string Pte_Nombres { get; set; }
        public string Pte_Apellidos { get; set; }
        public string Pte_Identidad { get; set; }
        public string Pte_Telefono { get; set; }
        public Nullable<System.DateTime> Pte_FechaSalida { get; set; }
        public Nullable<bool> Pte_FirmaUDM { get; set; }
        public Nullable<bool> Pte_FirmaMed { get; set; }
        public string Pte_UsuarioCrea { get; set; }
        public Nullable<System.DateTime> Pte_FechaCrea { get; set; }
        public string Pte_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> Pte_FechaModifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbBitacora> tbBitacora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPacienteXEspecialidad> tbPacienteXEspecialidad { get; set; }
    }
}
